# Generated by Django 4.2.17 on 2024-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_first_name_user_last_name_user_verify_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
